from typing import Protocol

from job_search_rss.domain.collection_condition import CollectionCondition
from job_search_rss.domain.condition_values import Occupation, Region
from job_search_rss.domain.history import CollectionRun, JobChange
from job_search_rss.domain.job import Job
from job_search_rss.domain.subscription_condition import SubscriptionCondition


class Repository(Protocol):
    def save_region(self, region: Region) -> None: ...

    def list_regions(self) -> list[Region]: ...

    def save_occupation(self, occupation: Occupation) -> None: ...

    def list_occupations(self) -> list[Occupation]: ...

    def save_job(self, job: Job) -> None: ...

    def list_jobs(self) -> list[Job]: ...

    def save_job_change(self, change: JobChange) -> None: ...

    def list_job_changes(self) -> list[JobChange]: ...

    def save_subscription_condition(self, condition: SubscriptionCondition) -> None: ...

    def list_subscription_conditions(self) -> list[SubscriptionCondition]: ...

    def save_collection_condition(self, condition: CollectionCondition) -> None: ...

    def list_collection_conditions(self) -> list[CollectionCondition]: ...

    def save_collection_run(self, run: CollectionRun) -> None: ...

    def list_collection_runs(self) -> list[CollectionRun]: ...

    def save_condition_snapshot(
        self,
        *,
        collection_condition_key: str,
        job_ids: list[str],
    ) -> None: ...

    def list_job_ids_for_condition(self, collection_condition_key: str) -> list[str]: ...
