from typing import Protocol

from job_search_rss.domain.collection_condition import CollectionCondition
from job_search_rss.domain.condition_values import Occupation, Region
from job_search_rss.domain.job import Job
from job_search_rss.domain.site_master import SiteOccupationMaster, SiteRegionMaster


class SiteAdapter(Protocol):
    def add_region(self, region: Region) -> None: ...

    def list_regions(self) -> list[Region]: ...

    def add_occupation(self, occupation: Occupation) -> None: ...

    def list_occupations(self) -> list[Occupation]: ...

    def list_site_region_masters(self) -> list[SiteRegionMaster]: ...

    def list_site_occupation_masters(self) -> list[SiteOccupationMaster]: ...

    def add_job_for_condition(self, condition: CollectionCondition, job: Job) -> None: ...

    def fetch_jobs_for_condition(self, condition: CollectionCondition) -> list[Job]: ...

    def fetch_job_detail(self, *, site_id: str, job_id: str) -> Job | None: ...
